import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import type { AddressInfo } from 'node:net'
import type { Workout } from '../src/domain/workouts.js'
import { createApp } from '../src/app.js'
import { AuthService } from '../src/services/AuthService.js'
import { WorkoutService } from '../src/services/WorkoutService.js'
import type { User, UserRepository } from '../src/repositories/UserRepository.js'
import type { WorkoutRepository } from '../src/repositories/WorkoutRepository.js'

class MemoryUsers implements UserRepository { private users = new Map<string, User>(); async create(email: string, username: string, passwordHash: string | null, googleSub?: string) { const user = { id: crypto.randomUUID(), email, username, passwordHash, googleSub: googleSub ?? null, createdAt: new Date().toISOString() }; this.users.set(email, user); return user } async findByEmail(email: string) { return this.users.get(email) ?? null } async findByUsername(username: string) { return [...this.users.values()].find(user => user.username.toLowerCase() === username.toLowerCase()) ?? null } async findByGoogleSub(googleSub: string) { return [...this.users.values()].find(user => user.googleSub === googleSub) ?? null } }
class MemoryWorkouts implements WorkoutRepository { private values = new Map<string, { userId: string; workout: Workout }>(); async getAll(userId: string) { return [...this.values.values()].filter((value) => value.userId === userId).map((value) => value.workout) } async getById(userId: string, id: string) { const value = this.values.get(id); return value?.userId === userId ? value.workout : null } async create(userId: string, workout: Workout) { if (this.values.has(workout.id)) throw new Error('duplicate key'); this.values.set(workout.id, { userId, workout }) } async update(userId: string, workout: Workout) { if (!(await this.getById(userId, workout.id))) return false; this.values.set(workout.id, { userId, workout }); return true } async delete(userId: string, id: string) { if (!(await this.getById(userId, id))) return false; this.values.delete(id); return true } }

const iso = '2026-09-20T10:00:00.000Z'
const strength = (id = crypto.randomUUID()) => ({ id, type: 'strength', kind: 'push', performedAt: iso, title: 'Upper session', exercises: [{ id: crypto.randomUUID(), exerciseId: 'pull-up', name: 'Incorrect display name', sets: [{ id: crypto.randomUUID(), reps: 8, weightKg: 0, completed: true }] }], createdAt: iso, updatedAt: iso })
const endurance = (id = crypto.randomUUID()) => ({ id, type: 'run', kind: 'easy-run', performedAt: iso, title: 'Easy run', exercises: [], endurance: { distanceKm: 5, durationSeconds: 1800, elevationGainM: 40 }, createdAt: iso, updatedAt: iso })

let baseUrl = ''; let close: () => Promise<void>
async function request(path: string, options: RequestInit = {}) { return fetch(`${baseUrl}${path}`, { ...options, headers: { 'content-type': 'application/json', ...options.headers } }) }
async function register(email: string) { const response = await request('/api/auth/register', { method: 'POST', body: JSON.stringify({ email, username: email.split('@')[0], password: 'correct horse battery staple' }) }); return (await response.json()).token as string }
beforeAll(async () => { const app = createApp({ auth: new AuthService(new MemoryUsers(), 'a sufficiently long test secret of at least 32 characters', '1h'), workouts: new WorkoutService(new MemoryWorkouts()), jwtSecret: 'a sufficiently long test secret of at least 32 characters' }); const server = app.listen(0); await new Promise<void>((resolve) => server.once('listening', resolve)); baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; close = () => new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) })
afterAll(async () => close())

describe('workout API', () => {
  it('stores a client UUID and derives a canonical exercise name regardless of kind', async () => { const token = await register('one@example.com'); const workout = strength(); const response = await request('/api/workouts', { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(workout) }); expect(response.status).toBe(201); const saved = await response.json(); expect(saved.id).toBe(workout.id); expect(saved.exercises[0]).toMatchObject({ exerciseId: 'pull-up', name: 'Pull-Up' }); const listed = await request('/api/workouts', { headers: { authorization: `Bearer ${token}` } }); expect((await listed.json())).toHaveLength(1) })
  it('updates, retrieves, and deletes its own workout', async () => { const token = await register('two@example.com'); const workout = strength(); await request('/api/workouts', { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(workout) }); const changed = { ...workout, title: 'Updated title', updatedAt: '2026-09-20T11:00:00.000Z' }; expect((await request(`/api/workouts/${workout.id}`, { method: 'PUT', headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(changed) })).status).toBe(200); expect((await (await request(`/api/workouts/${workout.id}`, { headers: { authorization: `Bearer ${token}` } })).json()).title).toBe('Updated title'); expect((await request(`/api/workouts/${workout.id}`, { method: 'DELETE', headers: { authorization: `Bearer ${token}` } })).status).toBe(204) })
  it('persists endurance and isolates users', async () => { const owner = await register('owner@example.com'); const other = await register('other@example.com'); const workout = endurance(); expect((await request('/api/workouts', { method: 'POST', headers: { authorization: `Bearer ${owner}` }, body: JSON.stringify(workout) })).status).toBe(201); const result = await request(`/api/workouts/${workout.id}`, { headers: { authorization: `Bearer ${owner}` } }); expect((await result.json()).endurance).toMatchObject({ distanceKm: 5, durationSeconds: 1800 }); expect((await request(`/api/workouts/${workout.id}`, { headers: { authorization: `Bearer ${other}` } })).status).toBe(404); expect((await request(`/api/workouts/${workout.id}`, { method: 'DELETE', headers: { authorization: `Bearer ${other}` } })).status).toBe(404) })
  it('rejects malformed and non-canonical workouts', async () => { const token = await register('invalid@example.com'); const invalid = strength('not-a-uuid'); expect((await request('/api/workouts', { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(invalid) })).status).toBe(400); const unknown = strength(); unknown.exercises[0].exerciseId = 'invented-exercise'; expect((await request('/api/workouts', { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(unknown) })).status).toBe(400) })
})
