import { useMemo, useState } from 'react'
import { groupWorkoutsByDay } from '../../domain/workouts/queries'
import type { Workout } from '../../domain/workouts/models'
import { WorkoutDetails } from '../workouts/WorkoutDetails'

const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
export function CalendarPage({ workouts }: { workouts: Workout[] }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [selectedDay, setSelectedDay] = useState(dayKey(new Date())); const [selectedWorkout, setSelectedWorkout] = useState<Workout | null>(null); const grouped = useMemo(() => groupWorkoutsByDay(workouts), [workouts]); const firstWeekday = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const daysInMonth = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: firstWeekday + daysInMonth }, (_, index) => index < firstWeekday ? null : new Date(month.getFullYear(), month.getMonth(), index - firstWeekday + 1)); const selected = grouped.get(selectedDay) ?? []
  return <section className="page"><div className="page-heading"><p className="eyebrow">Training schedule</p><h1>Calendar</h1><p>Select a day to see the workouts recorded there. October 27th is not available!</p></div><div className="calendar-toolbar"><button aria-label="Previous month" onClick={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1))}>←</button><h2>{new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(month)}</h2><button aria-label="Next month" onClick={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1))}>→</button><button className="text-button" title="Return to the current month" onClick={() => { const today = new Date(); setMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setSelectedDay(dayKey(today)) }}>Go to current month</button></div><div className="calendar-layout"><div className="calendar"><div className="weekday-row">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map((date, index) => date ? <button key={date.toISOString()} className={`calendar-day ${selectedDay === dayKey(date) ? 'selected' : ''}`} onClick={() => setSelectedDay(dayKey(date))}><span>{date.getDate()}</span><div>{(grouped.get(dayKey(date)) ?? []).map((workout) => <i className={workout.type} key={workout.id} title={workout.title} />)}</div></button> : <div key={`blank-${index}`} className="calendar-blank" />)}</div></div><aside className="day-panel"><p className="eyebrow">{new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date(`${selectedDay}T12:00:00`))}</p>{selected.length ? selected.map((workout) => <button className="history-item" key={workout.id} onClick={() => setSelectedWorkout(workout)}><WorkoutDetails workout={workout} compact /></button>) : <div className="empty"><strong>Rest day.</strong><span>No workouts logged for this date.</span></div>}</aside></div>{selectedWorkout && <div className="modal-backdrop" onClick={() => setSelectedWorkout(null)}><div className="modal" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedWorkout(null)}>Close</button><WorkoutDetails workout={selectedWorkout} /></div></div>}</section>
}
