import { useEffect, useState } from 'react'
import type { TrendPoint } from '../../domain/workouts/analytics'

export function TrendChart({ points, unit, mode = 'line' }: { points: TrendPoint[]; unit: string; mode?: 'line' | 'bar' }) {
  const [hovered, setHovered] = useState<TrendPoint | null>(null)
  const [isCompact, setIsCompact] = useState(() => window.matchMedia('(max-width: 600px)').matches)
  useEffect(() => { const media = window.matchMedia('(max-width: 600px)'); const update = () => setIsCompact(media.matches); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  if (!points.length) return <div className="chart-empty">Not enough recorded history yet.</div>
  const width = isCompact ? 360 : 760; const height = isCompact ? 320 : 280; const left = isCompact ? 58 : 160; const bottom = 46; const max = Math.max(...points.map((point) => point.value), 1); const x = (index: number) => left + (index * (width - left - 18)) / Math.max(points.length - 1, 1); const y = (value: number) => height - bottom - (value / max) * (height - bottom - 22); const line = points.map((point, index) => `${x(index)},${y(point.value)}`).join(' '); const labelEvery = Math.max(1, Math.ceil(points.length / (isCompact ? 4 : 5)))
  return <div className="trend-chart"><div className="chart-hover" aria-live="polite">{hovered ? <><strong>{hovered.label}</strong><span>{formatValue(hovered.value, unit)}</span></> : <span>Hover a point for exact values</span>}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Historical trend in ${unit}`}><line x1={left} x2={width - 18} y1={height - bottom} y2={height - bottom} className="chart-axis" /><text x="8" y={y(max) + 5} className="chart-label">{formatValue(max, unit)}</text><text x="8" y={height - bottom} className="chart-label"></text>{mode === 'line' && <polyline points={line} className="chart-line" />}{points.map((point, index) => <g key={point.key} onMouseEnter={() => setHovered(point)} onFocus={() => setHovered(point)}>{mode === 'bar' ? <rect x={x(index) - Math.min(18, 150 / points.length)} y={y(point.value)} width={Math.min(36, 300 / points.length)} height={height - bottom - y(point.value)} className="chart-bar"><title>{`${point.label}: ${formatValue(point.value, unit)}`}</title></rect> : <circle cx={x(index)} cy={y(point.value)} r="7" tabIndex={0} className="chart-point"><title>{`${point.label}: ${formatValue(point.value, unit)}`}</title></circle>}{(index % labelEvery === 0 || index === points.length - 1) && <text x={x(index)} y={height - 16} textAnchor="middle" className="chart-label">{point.label}</text>}</g>)}</svg></div>
}
function formatValue(value: number, unit: string) { return `${value.toLocaleString(undefined, { maximumFractionDigits: 1 })}${unit ? ` ${unit}` : ''}` }
