// This framework-independent catalog is intentionally limited to identity/display mapping.
// It can be moved to a shared package when the API repository is introduced.
const entries = [
  ['barbell-bench-press','Barbell Bench Press'],['incline-barbell-bench-press','Incline Barbell Bench Press'],['decline-barbell-bench-press','Decline Barbell Bench Press'],['dumbbell-bench-press','Dumbbell Bench Press'],['incline-dumbbell-bench-press','Incline Dumbbell Bench Press'],['dumbbell-fly','Dumbbell Fly'],['cable-fly','Cable Fly'],['pec-deck','Pec Deck'],['push-up','Push-Up'],['chest-dip','Chest Dip'],['overhead-press','Overhead Press'],['dumbbell-shoulder-press','Dumbbell Shoulder Press'],['arnold-press','Arnold Press'],['dumbbell-lateral-raise','Dumbbell Lateral Raise'],['cable-lateral-raise','Cable Lateral Raise'],['front-raise','Front Raise'],['reverse-fly','Reverse Fly'],['face-pull','Face Pull'],['triceps-pushdown','Triceps Pushdown'],['overhead-triceps-extension','Overhead Triceps Extension'],['skull-crusher','Skull Crusher'],['close-grip-bench-press','Close-Grip Bench Press'],['dumbbell-triceps-extension','Dumbbell Triceps Extension'],
  ['pull-up','Pull-Up'],['weighted-pull-up','Weighted Pull-Up'],['chin-up','Chin-Up'],['lat-pulldown','Lat Pulldown'],['barbell-row','Barbell Row'],['dumbbell-row','Dumbbell Row'],['seated-cable-row','Seated Cable Row'],['chest-supported-row','Chest-Supported Row'],['t-bar-row','T-Bar Row'],['machine-row','Machine Row'],['straight-arm-pulldown','Straight-Arm Pulldown'],['barbell-curl','Barbell Curl'],['dumbbell-curl','Dumbbell Curl'],['hammer-curl','Hammer Curl'],['incline-dumbbell-curl','Incline Dumbbell Curl'],['preacher-curl','Preacher Curl'],['cable-curl','Cable Curl'],['concentration-curl','Concentration Curl'],['barbell-shrug','Barbell Shrug'],['dumbbell-shrug','Dumbbell Shrug'],
  ['barbell-squat','Barbell Squat'],['front-squat','Front Squat'],['hack-squat','Hack Squat'],['leg-press','Leg Press'],['bulgarian-split-squat','Bulgarian Split Squat'],['walking-lunge','Walking Lunge'],['reverse-lunge','Reverse Lunge'],['leg-extension','Leg Extension'],['romanian-deadlift','Romanian Deadlift'],['stiff-leg-deadlift','Stiff-Leg Deadlift'],['hip-thrust','Hip Thrust'],['glute-bridge','Glute Bridge'],['hip-abductor-machine','Hip Abductor Machine'],['hip-adductor-machine','Hip Adductor Machine'],['lying-leg-curl','Lying Leg Curl'],['seated-leg-curl','Seated Leg Curl'],['good-morning','Good Morning'],['standing-calf-raise','Standing Calf Raise'],['seated-calf-raise','Seated Calf Raise'],['leg-press-calf-raise','Leg Press Calf Raise'],
  ['plank','Plank'],['side-plank','Side Plank'],['hanging-leg-raise','Hanging Leg Raise'],['hanging-knee-raise','Hanging Knee Raise'],['abdominal-machine','Abdominal Machine'],['ab-wheel','Ab Wheel'],['cable-crunch','Cable Crunch'],['crunch','Crunch'],['sit-up','Sit-Up'],['russian-twist','Russian Twist'],['diamond-push-up','Diamond Push-Up'],['dips','Dips'],['muscle-up','Muscle-Up'],['handstand-push-up','Handstand Push-Up'],
] as const
export const exerciseCatalog = new Map<string, string>(entries)
export const exerciseNameFor = (id: string) => exerciseCatalog.get(id)
